### PR TITLE
Missing part of the command

### PR DESCRIPTION
**Pull request by mrcai**

### CODE REVIEW

**Comment by KrauseFx** [comment]
Thanks for your contribution @mrcai, but `snapshot init` is the correct command 👍

**Comment by KrauseFx** [comment]
Or does it not work for you?

**Comment by matteocrippa** [comment]
I still have to prepend `fastlane` before, but I've to add that I'm using the latest version installed by fabric.

```
 ✘  ~  snapshot -v
fish: Unknown command 'snapshot'
```

```
 ~  fastlane snapshot -v
fastlane 1.12.3
```

**Comment by mrcai** [comment]
My thinking was as @matteocrippa stated. I can see the reasoning for leaving `fastlane` out too 👍

**Pull request closed without merging**
